"""
gloom/output.py
---------------
Collects pipeline outputs from the hidden .pipeline_cache/ directory and
reorganizes them into the clean, user-facing output structure:

    results/
    ├── candidates/
    │   ├── ranked_candidates.csv
    │   └── novel_candidates.csv
    ├── tables/
    │   ├── de_results.csv
    │   └── network_features.csv
    ├── models/
    │   ├── best_model.joblib
    │   └── model_card.json
    ├── plots/
    │   ├── volcano_plot.html
    │   ├── roc_pr_curves.html
    │   ├── feature_importance.html
    │   └── kegg_pathways.html
    ├── network/
    │   ├── coexpression.graphml
    │   └── coexpression.cytoscape.xml
    └── report.html
"""
import base64
import json
import logging
import shutil
from datetime import date
from pathlib import Path

log = logging.getLogger("gloom.output")


def organize_outputs(
    config,
    output_path: Path,
    disease: str = "luad",
    top_k: int | None = None,
    fmt: str = "csv",
) -> None:
    """
    Map pipeline cache outputs -> clean output directory.

    Parameters
    ----------
    config      : The (already-patched) pipeline config module.
    output_path : Root of the user-facing output directory.
    disease     : Disease label written into model_card.json.
    top_k       : If set, keep only the top N rows in candidate tables.
    fmt         : Output format for candidate tables — 'csv', 'excel', or 'json'.
    """
    _make_dirs(output_path)

    _candidates(config, output_path, top_k=top_k, fmt=fmt)
    _tables(config, output_path)
    _models(config, output_path, disease)
    _plots(config, output_path)
    _network(config, output_path)
    _report(config, output_path)

    log.info("Output structure ready.")
    _print_tree(output_path)


# ── Section builders ──────────────────────────────────────────────────────────

def _candidates(config, out: Path, top_k: int | None = None, fmt: str = "csv") -> None:
    import pandas as pd  # noqa: PLC0415

    d = out / "candidates"

    # Prefer the query-gene ranking (user's candidates scored by the model).
    # Fall back to the full ranking if no query genes were provided.
    query_rankings = Path(config.RESULTS_DIR) / "query_gene_rankings.csv"
    src = query_rankings if (query_rankings.exists() and query_rankings.stat().st_size > 0) \
          else Path(config.GENE_RANKINGS_FILE)

    novel_src = Path(config.RESULTS_DIR) / "novel_candidates.csv"

    for src_path, dst_stem in [(src, "ranked_candidates"), (novel_src, "novel_candidates")]:
        if not src_path.exists():
            log.warning(f"  MISSING (skipped): {src_path}")
            continue
        df = pd.read_csv(src_path, index_col=0)
        if top_k is not None:
            df = df.head(top_k)
        _save_table(df, d / dst_stem, fmt)
        log.info(f"  {src_path.name:50s} -> {dst_stem}.{_ext(fmt)}  ({len(df)} rows)")


def _tables(config, out: Path) -> None:
    d = out / "tables"
    _copy(config.DE_RESULTS_FILE,          d / "de_results.csv")
    _copy(config.NETWORK_FEATURES_FILE,    d / "network_features.csv")


def _models(config, out: Path, disease: str) -> None:
    d = out / "models"
    _copy(config.MODELS_DIR / "best_model.joblib", d / "best_model.joblib")
    _build_model_card(config, d / "model_card.json", disease)


def _plots(config, out: Path) -> None:
    d = out / "plots"
    _copy(config.FIGURES_DIR / "interactive_volcano.html",
          d / "volcano_plot.html")
    _copy(config.FIGURES_DIR / "interactive_feature_importance.html",
          d / "feature_importance.html")
    # interactive_kegg.html is generated by step 17 only when KEGG CSVs exist
    # (step 19 runs after step 17). Build it now from CSVs if not already done.
    kegg_html = Path(config.FIGURES_DIR) / "interactive_kegg.html"
    if not kegg_html.exists():
        _build_kegg_html(config, kegg_html)
    _copy(kegg_html, d / "kegg_pathways.html")
    _build_roc_pr_html(config, d / "roc_pr_curves.html")


def _network(config, out: Path) -> None:
    d = out / "network"
    src = Path(config.ANNOTATED_NETWORK_FILE)
    _copy(src, d / "coexpression.graphml")
    # Cytoscape 3+ reads GraphML natively — copy with .cytoscape.xml extension
    # so it can be imported directly via File -> Import -> Network from File
    _copy(src, d / "coexpression.cytoscape.xml")


def _report(config, out: Path) -> None:
    _copy(config.FIGURES_DIR / "interactive_dashboard.html", out / "report.html")
    # Embed KEGG chart inline into report.html using KEGG CSVs from step 19
    report = out / "report.html"
    if report.exists():
        _inject_kegg_tab(report, config)


# ── model_card.json ───────────────────────────────────────────────────────────

def _build_model_card(config, dst: Path, disease: str) -> None:
    """
    Generate a lightweight model card that describes the best model,
    its evaluation metrics, and key training parameters.
    """
    import pandas as pd  # noqa: PLC0415 — guarded import for optional environments

    card: dict = {
        "name":      "gloom-luad-prioritizer",
        "version":   __import__("gloom").__version__,
        "disease":   disease,
        "generated": str(date.today()),
    }

    # Best model name
    name_file = Path(config.MODELS_DIR) / "best_model_name.txt"
    if name_file.exists():
        card["best_model"] = name_file.read_text().strip()

    # Evaluation metrics (first row = best model, already sorted by AUPRC)
    metrics_file = Path(config.MODEL_METRICS_FILE)
    if metrics_file.exists():
        df = pd.read_csv(metrics_file)
        if not df.empty:
            row = df.iloc[0]
            scalar_cols = [
                "auroc", "auprc", "accuracy", "f1_optimal",
                "mcc", "brier_score", "threshold_optimal",
                "recall_at_50", "recall_at_100", "recall_at_200",
            ]
            card["metrics"] = {
                col: round(float(row[col]), 4)
                for col in scalar_cols
                if col in df.columns and not pd.isna(row[col])
            }

    # Key training parameters from config
    card["training_params"] = {
        "cv_folds":           config.CV_FOLDS,
        "cv_metric_primary":  config.CV_METRIC_PRIMARY,
        "threshold_strategy": config.THRESHOLD_STRATEGY,
        "use_smote":          config.USE_SMOTE,
        "use_undersampling":  config.USE_UNDERSAMPLING,
        "random_state":       config.RANDOM_STATE,
    }

    dst.write_text(json.dumps(card, indent=2))
    log.info(f"  model_card.json -> {dst}")


# ── roc_pr_curves.html ────────────────────────────────────────────────────────

def _build_roc_pr_html(config, dst: Path) -> None:
    """
    Create a self-contained HTML page that embeds the ROC and PR curve
    PNG figures as base64 data URIs (no external dependencies).
    """
    roc_png = Path(config.FIGURES_DIR) / "eval_roc_curves.png"
    pr_png  = Path(config.FIGURES_DIR) / "eval_pr_curves.png"

    sections = []
    for title, png_path in [("ROC Curves", roc_png), ("Precision-Recall Curves", pr_png)]:
        if not png_path.exists():
            log.warning(f"  {png_path.name} not found — skipping from roc_pr_curves.html")
            continue
        b64 = base64.b64encode(png_path.read_bytes()).decode()
        sections.append(
            f"<h2>{title}</h2>"
            f'<img src="data:image/png;base64,{b64}" '
            f'style="max-width:100%;border:1px solid #e0e0e0;border-radius:6px;">'
        )

    if not sections:
        log.warning("  No ROC/PR PNGs found — roc_pr_curves.html not created.")
        return

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>gloom — ROC &amp; PR Curves</title>
  <style>
    body  {{ font-family: system-ui, sans-serif; max-width: 1100px;
             margin: 2rem auto; padding: 0 1.5rem; color: #222; }}
    h1    {{ font-size: 1.6rem; border-bottom: 2px solid #4a90d9; padding-bottom: .4rem; }}
    h2    {{ font-size: 1.2rem; color: #4a90d9; margin-top: 2.5rem; }}
    img   {{ display: block; margin-bottom: 2rem; }}
  </style>
</head>
<body>
  <h1>Model Evaluation — ROC &amp; PR Curves</h1>
  {"".join(sections)}
</body>
</html>"""
    dst.write_text(html, encoding="utf-8")
    log.info(f"  roc_pr_curves.html -> {dst}")


# ── KEGG figure builder (shared by html file + dashboard injection) ───────────

def _build_kegg_figure(config):
    """Build and return a Plotly figure from KEGG CSVs produced by step 19.

    Returns None if Plotly is not installed or no significant data exists.
    """
    try:
        import numpy as np                  # noqa: PLC0415
        import pandas as pd                 # noqa: PLC0415
        import plotly.graph_objects as go   # noqa: PLC0415
    except ImportError:
        log.warning("  Plotly not installed — KEGG figure not built.")
        return None

    PADJ_CUTOFF = 0.05
    TOP_N = 15
    SUBSET_COLORS = {
        "All candidates": "#3A7DBF",
        "Upregulated":    "#E8524A",
        "Downregulated":  "#2CA07C",
    }

    kegg_files = [
        ("All candidates", getattr(config, "KEGG_ALL_FILE",  None)),
        ("Upregulated",    getattr(config, "KEGG_UP_FILE",   None)),
        ("Downregulated",  getattr(config, "KEGG_DOWN_FILE", None)),
    ]

    subsets = {}
    for label, fpath in kegg_files:
        if fpath and Path(fpath).exists():
            df = pd.read_csv(fpath)
            if not df.empty:
                if "neg_log10_padj" not in df.columns and "padj" in df.columns:
                    df["neg_log10_padj"] = -np.log10(df["padj"].clip(lower=1e-300))
                subsets[label] = df

    if not subsets:
        log.info("  No KEGG enrichment data found — skipping KEGG figure.")
        return None

    fig = go.Figure()
    subset_names = list(subsets.keys())
    has_traces = False

    for i, (label, df) in enumerate(subsets.items()):
        sig = df[df["padj"] < PADJ_CUTOFF].head(TOP_N).sort_values("neg_log10_padj")
        if sig.empty:
            continue
        has_traces = True
        color = SUBSET_COLORS.get(label, "#888888")

        def _hover(r, lbl=label):
            gene_str  = str(r.get("genes", ""))
            gene_prev = gene_str[:80] + "..." if len(gene_str) > 80 else gene_str
            return (
                f"<b>{r['pathway']}</b><br>Subset: {lbl}<br>"
                f"adj P: {r['padj']:.2e}<br>"
                f"-log10(padj): {r['neg_log10_padj']:.2f}<br>"
                f"Overlap: {r.get('overlap_genes','?')}/{r.get('pathway_size','?')}<br>"
                f"Odds Ratio: {float(r.get('odds_ratio', 0)):.2f}<br>"
                f"Genes: {gene_prev}"
            )

        fig.add_trace(go.Bar(
            x=sig["neg_log10_padj"], y=sig["pathway"],
            orientation="h", name=label, visible=(i == 0),
            marker=dict(
                color=sig["neg_log10_padj"],
                colorscale=[[0, "lightyellow"], [0.5, color], [1.0, color]],
                cmin=0, cmax=sig["neg_log10_padj"].max() or 1,
                showscale=(i == 0),
                colorbar=dict(title="-log10(padj)", thickness=14, len=0.7),
            ),
            text=sig["neg_log10_padj"].round(2), textposition="outside",
            customdata=sig.apply(_hover, axis=1).tolist(),
            hovertemplate="%{customdata}<extra></extra>",
        ))

    if not has_traces:
        log.info("  No significant KEGG pathways found — skipping KEGG figure.")
        return None

    buttons = []
    for i, name in enumerate(subset_names):
        buttons.append(dict(
            label=name, method="update",
            args=[{"visible": [j == i for j in range(len(subset_names))]},
                  {"title.text": f"<b>KEGG Pathway Enrichment - {name}</b>"}],
        ))
    buttons.append(dict(
        label="All subsets", method="update",
        args=[{"visible": [True] * len(subset_names)},
              {"title.text": "<b>KEGG Pathway Enrichment - All Subsets</b>"}],
    ))

    import numpy as np  # noqa: PLC0415
    fig.add_vline(x=-np.log10(PADJ_CUTOFF), line_dash="dash", line_color="grey",
                  line_width=1.5, annotation_text="padj=0.05",
                  annotation_position="top right", annotation_font_size=11)

    fig.update_layout(
        title=f"<b>KEGG Pathway Enrichment - {subset_names[0]}</b>",
        xaxis_title="-log10(adjusted p-value)", yaxis_title="KEGG Pathway",
        plot_bgcolor="white", paper_bgcolor="white",
        height=max(520, TOP_N * 36 + 160), width=1000,
        margin=dict(l=300, r=80, t=110, b=60),
        updatemenus=[dict(
            type="buttons", buttons=buttons, direction="right",
            showactive=True, x=0.0, xanchor="left", y=1.14, yanchor="top",
            bgcolor="#EEF3FA", bordercolor="#2D6A9F", font=dict(size=12),
        )],
        legend=dict(orientation="h", y=-0.18),
    )
    return fig


def _build_kegg_html(config, out_path: Path) -> None:
    """Write interactive_kegg.html from KEGG CSVs (standalone file)."""
    fig = _build_kegg_figure(config)
    if fig is None:
        return
    fig.write_html(str(out_path), include_plotlyjs="cdn")
    log.info(f"  interactive_kegg.html built from KEGG CSVs -> {out_path.name}")


# ── KEGG tab injection ────────────────────────────────────────────────────────

def _inject_kegg_tab(report: Path, config) -> None:
    """Embed the KEGG Plotly chart inline into report.html (idempotent)."""
    import plotly.io as pio  # noqa: PLC0415

    html = report.read_text(encoding="utf-8")
    if "KEGG Pathways" in html:
        return  # already present

    fig = _build_kegg_figure(config)
    if fig is None:
        log.info("  KEGG tab not added to report.html — no enrichment data.")
        return

    # Embed as inline div — Plotly JS is already loaded by the volcano plot
    kegg_div = pio.to_html(
        fig, full_html=False, include_plotlyjs=False,
        div_id="kegg_div", config={"responsive": True},
    )

    tab_button = (
        "  <div class=\"tab\"         onclick=\"showTab('kegg',this)\">KEGG Pathways</div>\n"
    )
    old_bar_end = (
        "  <div class=\"tab\"         onclick=\"showTab('novel',this)\">Novel Candidates</div>\n"
        "</div>"
    )
    new_bar_end = (
        "  <div class=\"tab\"         onclick=\"showTab('novel',this)\">Novel Candidates</div>\n"
        + tab_button
        + "</div>"
    )
    if old_bar_end not in html:
        log.warning("  Could not inject KEGG tab — tab-bar marker not found in report.html")
        return

    html = html.replace(old_bar_end, new_bar_end, 1)

    kegg_tab_content = (
        '\n<div id="tab-kegg" class="tab-content">\n'
        '  <div class="plot-card">\n'
        '    <div class="plot-desc"><b>KEGG Pathway Enrichment</b> &mdash; Novel LUAD candidates '
        'tested against KEGG_2021_Human via Enrichr, filtered to lung/cancer-relevant pathways. '
        'Use the buttons above the chart to switch between subsets. '
        'Hover a bar for pathway details and overlapping gene list.</div>\n'
        f'    {kegg_div}\n'
        '  </div>\n'
        '</div>'
    )
    html = html.replace(
        "<footer>LUAD ML Pipeline",
        kegg_tab_content + "\n<footer>LUAD ML Pipeline",
        1,
    )
    report.write_text(html, encoding="utf-8")
    log.info("  KEGG tab embedded inline into report.html")


# ── Utilities ─────────────────────────────────────────────────────────────────

def _make_dirs(out: Path) -> None:
    for sub in ("candidates", "tables", "models", "plots", "network"):
        (out / sub).mkdir(parents=True, exist_ok=True)


def _ext(fmt: str) -> str:
    return {"csv": "csv", "excel": "xlsx", "json": "json"}[fmt]


def _save_table(df, dst_stem: Path, fmt: str) -> None:
    """Save a DataFrame to dst_stem.<ext> in the requested format."""
    import pandas as pd  # noqa: PLC0415
    ext = _ext(fmt)
    dst = dst_stem.with_suffix(f".{ext}")
    if fmt == "csv":
        df.to_csv(dst)
    elif fmt == "excel":
        df.to_excel(dst, engine="openpyxl")
    elif fmt == "json":
        df.to_json(dst, orient="records", indent=2)


def _copy(src, dst: Path) -> None:
    src = Path(src)
    if src.exists():
        shutil.copy2(src, dst)
        log.info(f"  {src.name:50s} -> {dst.relative_to(dst.parent.parent)}")
    else:
        log.warning(f"  MISSING (skipped): {src}")


def _print_tree(out: Path) -> None:
    log.info("")
    log.info(f"{out.name}/")
    for f in sorted(out.rglob("*")):
        if f.is_file() and ".pipeline_cache" not in str(f):
            rel = f.relative_to(out)
            depth = len(rel.parts) - 1
            indent = "    " * depth
            log.info(f"  {indent}├── {f.name}")
    log.info("")
